### ISSUE TITLE
Should the developer docs still reference the Gitter channel, or perhaps Slack or Discord?

### ISSUE THREAD

**Issue by 00krishna** [SciML/DiffEqDevDocs.jl#27]
Hello all. 

I was just looking through the developer docs and I noticed the line. This is a really small item, but hopefully every bit helps. 

`So you're looking to help out DifferentialEquations.jl? We'd be happy to have your help. It is recommended you first discuss with some of the developers [on the Gitter channel](https://gitter.im/JuliaDiffEq/Lobby) to make sure that you're up-to-date with current developments.`

on page https://devdocs.sciml.ai/latest/contributing/ecosystem_overview/

I was just wondering if the docs should still reference the Gitter channel, or perhaps Slack or Discord? I can make the change in the docs if the development doc owners want to change the link. If the owners want to keep the docs as is, that is fine and the issue can be closed.

**Comment by ChrisRackauckas** [comment]
We should probably be referencing Slack, Discord, and Zulip

**Comment by 00krishna** [comment]
Cool. I will look up the links and put in a PR. Should I encourage users to use one network more than others? Seems like most folks are on Slack. But this is also just me checking to make sure I don't add more work for you--having to check 3 networks. I can just set this up and submit it, and you can indicate your preference then.

**Comment by ChrisRackauckas** [comment]
There's a bot that links them, so it really doesn't matter. Only the Discord is separate.
