### ISSUE TITLE
Doc build failure

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqDevDocs.jl#29]
@ranocha do you know how to handle https://github.com/SciML/DiffEqDevDocs.jl/actions/runs/3294615542/jobs/5432308785#step:5:800 ?

**Comment by ranocha** [comment]
Looks quite weird - could you update the Julia version? Version 1.3.1 is quite old...

**Comment by ChrisRackauckas** [comment]
oh interesting...
