### ISSUE TITLE
"type" in julia md block

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqDevDocs.jl#49]
This is not valid Julia code, which can be formatted:
https://github.com/SciML/DiffEqDevDocs.jl/blob/master/docs/src/alg_dev/test_problems.md?plain=1#L14

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqDevDocs.jl/commit/164b7792e3cdce120388e818c867fba321867fc1
